from typing import Protocol
from uuid import UUID

from app.infrastructure.database.models import EntityFieldModel, EntityModel


class MetadataRepositoryProtocol(Protocol):
    async def create_entity(self, entity: EntityModel) -> EntityModel: ...
    async def get_entity_by_id(self, entity_id: UUID) -> EntityModel | None: ...
    async def get_entity_by_name(self, name: str) -> EntityModel | None: ...
    async def get_all_entities(self) -> list[EntityModel]: ...
    async def update_entity(self, entity: EntityModel) -> EntityModel: ...
    async def delete_entity(self, entity_id: UUID) -> bool: ...
    async def create_field(self, field: EntityFieldModel) -> EntityFieldModel: ...
    async def get_field_by_id(self, field_id: UUID) -> EntityFieldModel | None: ...
    async def delete_field(self, field_id: UUID) -> bool: ...


class TableManagerProtocol(Protocol):
    async def create_table(self, table_name: str) -> None: ...
    async def add_column(self, table_name: str, column_name: str, field_type: str, max_length: int | None) -> None: ...
    async def drop_column(self, table_name: str, column_name: str) -> None: ...
    async def drop_table(self, table_name: str) -> None: ...
